# Generated by Django 2.0.7 on 2018-07-08 12:42

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180708_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='UserName',
        ),
        migrations.AlterField(
            model_name='post',
            name='CurrentUser',
            field=models.CharField(blank=True, default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=120, null=True),
        ),
    ]
