# Generated by Django 2.0.7 on 2018-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180708_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CurrentUser',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
